# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Check whether the parameter F is within the appropriate range
#' 
#' @param turboF F (converted for turboEM)
#' @param fdim a vector specifying the number of possible values for each mutation signature
#' @param signatureNum the number of mutation signatures
#' @export
boundaryTurbo_F <- function(turboF, fdim, signatureNum) {
    .Call('pmsignature_boundaryTurbo_F', PACKAGE = 'pmsignature', turboF, fdim, signatureNum)
}

#' Check whether the parameter Q is within the appropriate range
#' 
#' @param turboQ Q (converted for turboEM)
#' @param signatureNum the number of mutation signatures
#' @param sampleNum the number of cancer genomes
#' @export
boundaryTurbo_Q <- function(turboQ, signatureNum, sampleNum) {
    .Call('pmsignature_boundaryTurbo_Q', PACKAGE = 'pmsignature', turboQ, signatureNum, sampleNum)
}

#' Convert the parameter Q so that turboEM can treat
#' 
#' @param vQ Q (converted to a vector)
#' @param signatureNum the number of mutation signatures
#' @param sampleNum the number of cancer genomes
#' @export
convertToTurbo_Q <- function(vQ, signatureNum, sampleNum) {
    .Call('pmsignature_convertToTurbo_Q', PACKAGE = 'pmsignature', vQ, signatureNum, sampleNum)
}

#' Convert the parameter F so that turboEM can treat
#' 
#' @param vF F (converted to a vector)
#' @param fdim a vector specifying the number of possible values for each mutation signature
#' @param signatureNum the number of mutation signatures
#' @param isBackground the logical value showing whether a background mutaiton features is included or not
#' @export
convertToTurbo_F <- function(vF, fdim, signatureNum, isBackground) {
    .Call('pmsignature_convertToTurbo_F', PACKAGE = 'pmsignature', vF, fdim, signatureNum, isBackground)
}

#' Restore the converted parameter Q for turboEM
#' 
#' @param turboQ Q (converted for turboEM)
#' @param signatureNum the number of mutation signatures
#' @param sampleNum the number of cancer genomes
#' @export
convertFromTurbo_Q <- function(turboQ, signatureNum, sampleNum) {
    .Call('pmsignature_convertFromTurbo_Q', PACKAGE = 'pmsignature', turboQ, signatureNum, sampleNum)
}

#' Restore the converted parameter F for turboEM
#' 
#' @param turboF F (converted for turboEM)
#' @param fdim a vector specifying the number of possible values for each mutation signature
#' @param signatureNum the number of mutation signatures
#' @param sampleNum the number of cancer genomes
#' @param isBackground the logical value showing whether a background mutaiton features is included or not
#' @export
convertFromTurbo_F <- function(turboF, fdim, signatureNum, isBackground) {
    .Call('pmsignature_convertFromTurbo_F', PACKAGE = 'pmsignature', turboF, fdim, signatureNum, isBackground)
}

#' Update the auxiliary parameters theta and normalize them so that the summation of each group sums to 1 (E-step)
#' 
#' @param vF F (converted to a vector)
#' @param vQ Q (converted to a vector)
#' @param fdim a vector specifying the number of possible values for each mutation signature
#' @param signatureNum the number of mutation signatures
#' @param sampleNum the number of cancer genomes
#' @param patternNum the number of possible combinations of all the mutation features
#' @param isBackground the logical value showing whether a background mutaiton features is included or not
#' @param vF0 a background mutaiton features
#' @export
updateTheta_NormalizedC <- function(vF, vQ, fdim, signatureNum, sampleNum, patternNum, isBackground, vF0) {
    .Call('pmsignature_updateTheta_NormalizedC', PACKAGE = 'pmsignature', vF, vQ, fdim, signatureNum, sampleNum, patternNum, isBackground, vF0)
}

#' Calculate the value of the log-likelihood for given parameters
#' 
#' @param vG the matrix of mutation feature data
#' @param vF the parameter F (converted to a vector)
#' @param vQ the parameter Q (converted to a vector)
#' @param fdim a vector specifying the number of possible values for each mutation signature
#' @param signatureNum the number of mutation signatures
#' @param sampleNum the number of cancer genomes
#' @param patternNum the number of possible combinations of all the mutation features
#' @param isBackground the logical value showing whether a background mutaiton features is included or not
#' @param vF0 a background mutaiton features
#' @export
getLogLikelihoodC <- function(vG, vF, vQ, fdim, signatureNum, sampleNum, patternNum, isBackground, vF0) {
    .Call('pmsignature_getLogLikelihoodC', PACKAGE = 'pmsignature', vG, vF, vQ, fdim, signatureNum, sampleNum, patternNum, isBackground, vF0)
}

#' Update the parameter F (M-step in the EM-algorithm)
#' 
#' @param vTheta theparameter Theta (converted to a vector)
#' @param vG the matrix of mutation feature data
#' @param fdim a vector specifying the number of possible values for each mutation signature
#' @param signatureNum the number of mutation signatures
#' @param sampleNum the number of cancer genomes
#' @param patternNum the number of possible combinations of all the mutation features
#' @param isBackground the logical value showing whether a background mutaiton features is included or not
#' @export
updateMstepFC <- function(vTheta, vG, fdim, signatureNum, sampleNum, patternNum, isBackground) {
    .Call('pmsignature_updateMstepFC', PACKAGE = 'pmsignature', vTheta, vG, fdim, signatureNum, sampleNum, patternNum, isBackground)
}

#' Update the parameter Q (M-step in the EM-algorithm)
#' 
#' @param vTheta theparameter Theta (converted to a vector)
#' @param vG the matrix of mutation feature data
#' @param signatureNum the number of mutation signatures
#' @param sampleNum the number of cancer genomes
#' @param patternNum the number of possible combinations of all the mutation features
#' @export
updateMstepQC <- function(vTheta, vG, signatureNum, sampleNum, patternNum) {
    .Call('pmsignature_updateMstepQC', PACKAGE = 'pmsignature', vTheta, vG, signatureNum, sampleNum, patternNum)
}

